### ISSUE TITLE
[Feature Request] Minimizing Request Headers

### ISSUE THREAD

**Issue by Anon-Exploiter** [ngo/burp-request-minimizer#6]
Hi, 

Thanks for the extension, it really helps in saving time and not doing stuff manually. With that, can you please add an option in the extension to minimize the request headers as well while keeping the workflow same. 

I know it's currently not intended but if possible, can you please take a look into this request?

**Comment by solidfan** [comment]
Hello, glad that it helped.
I'm not sure I'll be able to look into that very soon, but hopefully in a couple of weeks I can manage to find time.

That being said, th fix itself shouldn't be that hard, because I have all the logic for header manipulation ready in https://github.com/ngo/burp-request-minimizer/blob/master/minimizer.py#L47

**Comment by ngo** [comment]
Hello, glad that it helped.
I'm not sure I'll be able to look into that very soon, but hopefully in a couple of weeks I can manage to find time.

That being said, th fix itself shouldn't be that hard, because I have all the logic for header manipulation ready in https://github.com/ngo/burp-request-minimizer/blob/master/minimizer.py#L47

**Comment by Anon-Exploiter** [comment]
Hi, 

Thanks for considering it, it'll be cool to have the functionality. Will wait :grin:

**Comment by Anon-Exploiter** [comment]
Hey @ngo, 

Hope you're doing well, was wondering if you got time to look into this?

**Comment by ngo** [comment]
Hello @Anon-Exploiter, unfortunately haven't got time to implement it yet, but this is still in the backlog.

**Comment by Anon-Exploiter** [comment]
Thanks, re-opening the request.

**Comment by Anon-Exploiter** [comment]
:grimacing:
